"""Writes each app's copy of shared/app_data.json as code.

    python shared/generate.py           # regenerate
    python shared/generate.py --check   # exit 1 if a generated file is out of date (CI)

Outputs:
    lib/src/generated/app_data.dart           (phone and desktop)
    roku/app/source/generated/app_data.brs    (Roku)

Generated code rather than each app reading the JSON: Flutter needs icons as
constants (a release build strips unused icons from the font and can't when
they're looked up at runtime), and doing both the same way keeps them alike.
The Roku's icon images come from the same `icon` names via
roku/tools/make_assets.py.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'shared', 'app_data.json')
DART = os.path.join(ROOT, 'lib', 'src', 'generated', 'app_data.dart')
BRS = os.path.join(ROOT, 'roku', 'app', 'source', 'generated', 'app_data.brs')

HEADER = 'GENERATED by shared/generate.py from shared/app_data.json. Edit that file, not this one.'


def load():
    with open(DATA, encoding='utf-8') as f:
        data = json.load(f)
    sports = {k: v for k, v in data['sports'].items() if not k.startswith('_')}
    sources = data['sources']['order']
    palette = {k: v for k, v in data['palette'].items() if not k.startswith('_')}
    return sports, data['defaultSportIcon'], sources, palette


def q(s):
    """A BrightScript string literal."""
    return json.dumps(s, ensure_ascii=False)


def dq(s):
    """A Dart string literal, in the project's single-quote style."""
    for c in ('\\', "'", '$'):
        s = s.replace(c, '\\' + c)
    return "'" + s + "'"


def dart(sports, default_icon, sources, palette):
    out = [
        f'// {HEADER}',
        '// ignore_for_file: constant_identifier_names',
        '',
        "import 'package:flutter/material.dart';",
        '',
        '/// Sport display names that differ from the API\'s, by sport id.',
        'const Map<String, String> sportDisplayNames = <String, String>{',
    ]
    out += [f'  {dq(k)}: {dq(v["name"])},' for k, v in sports.items() if 'name' in v]
    out += ['};', '', '/// Sport icons by sport id; [defaultSportIcon] for any other.', 'const Map<String, IconData> sportIcons = <String, IconData>{']
    out += [f'  {dq(k)}: Icons.{v["icon"]},' for k, v in sports.items()]
    out += ['};', f'const IconData defaultSportIcon = Icons.{default_icon};', '']
    out += ['/// Stream sources, best first; sources not listed go last.', 'const List<String> sourceOrder = <String>[']
    out += [f'  {dq(s["id"])},' for s in sources]
    out += ['];', '', '/// The site\'s description of each source.', 'const Map<String, String> sourceDescriptions = <String, String>{']
    out += [f'  {dq(s["id"])}: {dq(s["description"])},' for s in sources]
    out += ['};', '', '/// Colours both apps use: the dark theme, and the light theme\'s version where there is one.', 'abstract final class AppPalette {']
    for name, v in palette.items():
        out.append(f'  static const Color {name} = Color(0xFF{v["dark"][1:].upper()});')
        if 'light' in v:
            out.append(f'  static const Color {name}Light = Color(0xFF{v["light"][1:].upper()});')
    out += ['}', '']
    return '\n'.join(out)


def brs(sports, default_icon, sources, palette):
    def aa(pairs):
        return '{' + ', '.join(f'{q(k)}: {q(v)}' for k, v in pairs) + '}'
    out = [f"' {HEADER}", '']
    out += ["' Sport display names that differ from the API's, by sport id.",
            'function appSportDisplayNames() as Object',
            '    return ' + aa((k, v['name']) for k, v in sports.items() if 'name' in v),
            'end function', '',
            "' Sport icons (Material icon names; images/icons/<name>.png) by sport id.",
            'function appSportIcons() as Object',
            '    return ' + aa((k, v['icon']) for k, v in sports.items()),
            'end function', '',
            'function appDefaultSportIcon() as String',
            f'    return {q(default_icon)}',
            'end function', '',
            "' Stream sources, best first; sources not listed go last.",
            'function appSourceOrder() as Object',
            '    return [' + ', '.join(q(s['id']) for s in sources) + ']',
            'end function', '',
            "' The site's description of each source.",
            'function appSourceDescriptions() as Object',
            '    return ' + aa((s['id'], s['description']) for s in sources),
            'end function', '',
            "' The dark theme's colours (the Roku's only theme).",
            'function appPalette() as Object',
            '    return ' + aa((k, '0x' + v['dark'][1:].upper() + 'FF') for k, v in palette.items()),
            'end function', '']
    return '\n'.join(out)


def main():
    sports, default_icon, sources, palette = load()
    wanted = {DART: dart(sports, default_icon, sources, palette), BRS: brs(sports, default_icon, sources, palette)}
    check = '--check' in sys.argv
    stale = []
    for path, text in wanted.items():
        current = None
        if os.path.exists(path):
            with open(path, encoding='utf-8', newline='') as f:
                current = f.read().replace('\r\n', '\n')
        if current == text:
            continue
        if check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print('wrote', os.path.relpath(path, ROOT))
    if stale:
        print('Out of date (run `python shared/generate.py` and commit):', ', '.join(stale))
        sys.exit(1)


if __name__ == '__main__':
    main()
